# Generated by Django 4.2.4 on 2023-08-18 03:48

from django.db import migrations, models
import member_info_capture.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('new', 'New Student'), ('returning', 'Returning Student')], default='new', max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('personal_email', models.EmailField(max_length=254, validators=[member_info_capture.models.validate_email])),
                ('residential_address', models.CharField(max_length=200)),
                ('system_email', models.EmailField(default='default_value', max_length=254, unique=True)),
                ('id_number', models.CharField(default='default_value', max_length=13, validators=[member_info_capture.models.validate_id_number])),
                ('user_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
