# Generated by Django 4.2.4 on 2023-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info_capture', '0002_alter_member_system_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='system_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
